import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import LiquidEther from '../components/LiquidEther';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "s2mh",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div style={{ width: '100%', height: 1800, position: 'fixed' }}>
          <LiquidEther
            mouseForce={20}
            cursorSize={100}
            isViscous={false}
            viscous={30}
            iterationsViscous={32}
            iterationsPoisson={32}
            resolution={0.5}
            isBounce={false}
            autoDemo={true}
            autoSpeed={0.5}
            autoIntensity={2.2}
            takeoverDuration={0.25}
            autoResumeDelay={3000}
            autoRampDuration={0.6}
          />
        </div>
        {children}
        </body>
    </html>
  );
}
